version: "3.8"

services:
    mysql_auth:
        image: mysql:5.7
        volumes:
            - simple-login-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: toor
            MYSQL_PASSWORD: toor
            MYSQL_DATABASE: simple_auth
        ports:
            - "33006:3306"
        restart: on-failure

    server:
        build:
            dockerfile: Dockerfile
            context: "./Server"
        volumes:
            - simple-login-server-data:/var/www/html
        depends_on:
            - mysql_auth
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: toor
            MYSQL_PASSWORD: toor
            MYSQL_DATABASE: LoginSystem
        ports:
            - "3001:3001"
        restart: always

    client:
        build:
            dockerfile: Client/Dockerfile_dev__
            context: "./Client"
        volumes:
            - simple-login-client-data:/var/www/html
        depends_on:
            - server
        ports:
            - "3000:3000"
volumes:
    simple-login-mysql-data:
    simple-login-server-data:
    simple-login-client-data: