version: "3.8"

services:
    mysql:
        image: mysql:5.7
        volumes:
            - simple-login-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: LoginSystem
            MYSQL_TCP_PORT: 3001
        ports:
            - "3306:3001"
        expose:
            - "3001"
volumes:
    simple-login-mysql-data: