version: "3.8"

services:
#    mysql_auth:
#        container_name: "mysql-auth"
#        image: mysql
#        restart: always
#        cap_add:
#            - SYS_NICE
#        volumes:
#            - simple-login-mysql-auth-data:/var/lib/mysql
#        ports:
#            - "33006:3306"
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_USER: toor
#            MYSQL_PASSWORD: toor
#            MYSQL_DATABASE: db_auth
#            MYSQL_HOST: localhost

    mysql_board:
        container_name: "mysql-board"
        image: mysql
        restart: always
        cap_add:
            - SYS_NICE
        volumes:
            - simple-login-mysql-board-data:/var/lib/mysql
        ports:
            - "33007:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: toor
            MYSQL_PASSWORD: toor
            MYSQL_DATABASE: db_board
            MYSQL_HOST: localhost

    api:
        build:
            dockerfile: Dockerfile
            context: "./Server"
        depends_on:
            - mysql_auth
        volumes:
            - /app/node_modules
            - ./Server:/app
#            - simple-login-server-data:/app
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: toor
            MYSQL_PASSWORD: toor
#            MYSQL_DATABASE: db_auth
#            MYSQL_HOST_IP: mysql_auth
            MYSQL_DATABASE: db_board
            MYSQL_HOST_IP: mysql_board

    client:
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            dockerfile: Dockerfile
            context: ./Client
        volumes:
            - /app/node_modules
            - ./Client:/app
#            - simple-login-client-data:/app

    nginx-prod:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "3009:80"

    adminer:
        image: adminer:latest
        restart: unless-stopped
        ports:
            - "8000:8080"
        depends_on:
            - mysql_auth
        environment:
            ADMINER_DEFAULT_SERVER: mysql_auth
volumes:
    simple-login-mysql-auth-data:
    simple-login-mysql-board-data:
#    simple-login-server-data:
#    simple-login-client-data: